version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearchh
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.2
    container_name: logstashh
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: kibanaa
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  mongo:
    image: mongo:6.0
    container_name: mongodbb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: rediss
    ports:
      - "6380:6380"

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_appp
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - logstash
      - kibana
      - mongo
      - redis

volumes:
  mongo_data: